### ISSUE TITLE
get_device_data.py is only returning None.json

### ISSUE THREAD

**Issue by cdjm** [danielperna84/pydevccu#23]
Hello,

I wanted to submit the device data for HM-RC-2-PBU-FM, but I get only two None.json files when running the get_device_data.py (no matter which device I choose).

The output from the script is not very helpful:

```
Saving device of type None to:
/Users/someone/device_descriptions/None.json
/Users/someone/paramset_descriptions/None.json
```

Can you tell me what is required to run this script?

I'm executing the script from a Mac running Python 3.8.2.
My CCU3 runs Raspberrymatic 3.59.6.20210703.

Am I missing something?

**Comment by danielperna84** [comment]
This usually happens when you previously executed the script without being properly configured. On first start the script creates a cache of all devices found on the CCU. If it fails to get the data, it will create an empty cache-file. Therefor if will fail to find the data later on. You should find the cache file next to the script. Delete and try again. 👍

**Comment by cdjm** [comment]
Thank you for the quick answer.
This brought me on the right track.

I tried removing the device_cache.json. 
It gets recreated again but only contains some of the devices.

Checking this file more closely there were only  HmIP devices included. 
All my Homematic RF devices were missing.

In case someone else has this problem:
The script only retrieves the devices known by under the named port (default is 2010 for HmIP).
Before switching to port 2001 for the HM-RF devices the cache file must be deleted.
The cache file from port 2001 then contains all the HM-RF devices.

Got the device files and will post them later on the pyhomematic github.

Problem solved.
