### ISSUE TITLE
Support HM-LC-AO-SM

### ISSUE THREAD

**Issue by bennyb21** [danielperna84/pydevccu#32]
I´m using two of the rare 0-10V Actuators for dimming lights with Meanwell Powersupplys. Inside HA I can´t use the Level to switch them on or off. They are shown as number entitys. 

I saw the Device is listed as supported. But as said, these are rare. Perhaps nobody had an issue with the Device in HA until now. The only way to control them by now is in NodeRed by setting the Level. But no Automations are working with this Device. Also they are not supported to control them with the Alexa Integration. It might also be a Problem with the Person in front of the Monitor...

[HM-LC-AO-SM.zip](https://github.com/danielperna84/pydevccu/files/10192597/HM-LC-AO-SM.zip)

**Comment by SukramJ** [comment]
This is the wrong repo to ask for device support in HA. 
Pydevccu is a virtual ccu that can be used for testing, so device definitions are always welcome, but HM-LC-AO-SM is already there.

> I saw the Device is listed as supported

Where did you saw this?

The device integration for [custom homematic](https://github.com/danielperna84/custom_homematic) (new homematic integration) is done in [hahomematic](https://github.com/danielperna84/hahomematic/). There are also corresponding links in the documentation for custom_component.
A FR no longer needs to be created for HM-LC-AO-SM since I saw this entry.

Please close the issue here.

**Comment by bennyb21** [comment]
Thanks for the Reply!

I saw [this](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) Information in the custom homematic repo. But it seems I missunderstood it. In the same Wiki further up is mentioned to make a FR in the hahomatic repo. 

> Where did you saw this?
Here in this repo inside the device_descriptions.

Thanks for taking care!
